Repository palantir/gradle-guide, pull requests merged in 2025-03, with the labels that each got.

#59 Delete unused code
  gradle-guide/build.gradle
  gradle-guide/src/main/java/com/palantir/gradle/guide/ConfigFile.java
  gradle-guide/src/main/java/com/palantir/gradle/guide/EnableChecksThatPass.java
  versions.lock
Labels: no changelog

#58 Initial errorprones for lazy task creation
  build.gradle
  changelog/@unreleased/pr-58.v2.yml
  errorprones.md
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/ConfigurationAvoidanceRegistration.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/GradleGuideBugChecker.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/RegisterInsteadOfCreate.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/besteffort/ProviderImprovements.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/utils/AllErrorprones.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/utils/ReplacementTracker.java
  gradle-guide-error-prone/src/main/java/com/palantir/gradle/guide/errorprone/utils/TreeUtils.java
  gradle-guide-error-prone/src/test/groovy/com/palantir/gradle/guide/errorprone/RegisterInsteadOfCreateTest.groovy
  gradle-guide-error-prone/src/test/java/com/palantir/gradle/guide/besteffort/ProviderImprovementsTest.java
  gradle-guide-error-prone/src/test/java/com/palantir/gradle/guide/checks/AllErrorpronesExtendFromGradleGuideBugCheckerTest.java
  gradle-guide-error-prone/src/test/java/com/palantir/gradle/guide/errorprone/ConfigurationAvoidanceRegistrationTest.java
  gradle-guide-error-prone/src/test/java/com/palantir/gradle/guide/helpers/RefactoringValidator.java
  gradle-guide/src/main/java/com/palantir/gradle/guide/GradleGuidePlugin.java
  gradle-guide/src/test/groovy/com/palantir/gradle/guide/GradleGuidePluginIntegrationSpec.groovy
  internal-checks/src/main/java/com/palantir/gradle/guide/internal/errorprone/ErrorpronePermalinksGenerator.java
  internal-checks/src/test/java/com/palantir/gradle/guide/internal/errorprone/AllErrorpronesHaveValidMoreInfoLinksTest.java
  internal-checks/src/test/java/com/palantir/gradle/guide/internal/errorprone/ErrorpronePermalinksGeneratorTest.java
  versions.lock
  versions.props
Labels: merge when ready

#76 switch to git version over circle tag
  changelog/@unreleased/pr-76.v2.yml
  guide/testing-and-running-your-plugins-locally.md
Labels: autorelease, merge when ready
